stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build-system:
  stage: build
  script:
    - nix-build '<nixpkgs/nixos>' -o result-$CI_JOB_NAME -A system -I nixpkgs=$(pwd)/nixpkgs -I nixos-config=$(pwd)/configuration.nix-$CI_JOB_NAME -I nixpkgs-overlays=$(pwd)/overlay --keep-going

balthamel:
  extends: .build-system

ishamael:
  extends: .build-system

amon:
  extends: .build-system

naberius:
  extends: .build-system

# kodi:
#   extends: .build-system

deploy-amon:
  stage: deploy
  only:
    - master
  script:
    - nixops modify ./nixops/cd-amon.nix ./nixops/cd-amon-deployment.nix -d cd-amon  -I nixpkgs=$(pwd)/nixpkgs -I nixos-config=$(pwd)/configuration.nix-$CI_JOB_NAME -I nixpkgs-overlays=$(pwd)/overlay || nixops create ./nixops/cd-amon.nix ./nixops/cd-amon-deployment.nix -d cd-amon  -I nixpkgs=$(pwd)/nixpkgs -I nixos-config=$(pwd)/configuration.nix-$CI_JOB_NAME -I nixpkgs-overlays=$(pwd)/overlay
    - nixops deploy -d cd-amon --option extra-builtins-file $(pwd)/nixops/extra-builtins.nix
