# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/ishamael/root";
      fsType = "btrfs";
      options = [ "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partlabel/ishamael-boot";
      fsType = "vfat";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/ishamael/root";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  swapDevices = [ {device = "/dev/disk/by-label/ishamael-swap"; } ];

  nix.maxJobs = 4;
}
