on:
  schedule:
    - cron: "13 10 * * Mon"
  workflow_dispatch: {}

jobs:
  define-matrix:
    runs-on: native
    outputs:
      configurations: ${{ steps.define.outputs.configurations }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: unlock git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: git crypt unlock <(echo "$GIT_CRYPT_KEY"|base64 -d)
      - id: define
        run: |
          echo "configurations=$(nix run .#ncf -- ci matrix)" >> "$FORGEJO_OUTPUT"

  update-and-build:
    runs-on: native
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        nixosConfiguration: ${{ fromJSON(needs.define-matrix.outputs.configurations) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: unlock git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: git crypt unlock <(echo "$GIT_CRYPT_KEY"|base64 -d)
      - name: Update flake inputs
        run: nix flake update
      - name: give autofollow a chance to mess with flake.lock
        run: nix run .#write-flake
      - name: Build ${{ matrix.nixosConfiguration }}
        run: nix run .#ncf -- build nixos ${{ matrix.nixosConfiguration }} --no-nom -o temp-result/${{ matrix.nixosConfiguration }}
      - name: Add GC root for ${{ matrix.nixosConfiguration }}
        run: |
          mkdir -p "$HOME/.cache/nixos-config/proposed-update/nixos-configuration"
          nix-store --add-root "$HOME/.cache/nixos-config/proposed-update/nixos-configuration/${{ matrix.nixosConfiguration }}" \
            -r "$(readlink -f "temp-result/${{ matrix.nixosConfiguration }}")"

  check-and-push:
    runs-on: native
    needs:
      - update-and-build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: unlock git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: git crypt unlock <(echo "$GIT_CRYPT_KEY"|base64 -d)
      - name: Update flake inputs
        run: nix flake update
      - name: give autofollow a chance to mess with flake.lock
        run: nix run .#write-flake
      - name: Set git username for commits
        run: git config user.name "Automatic Flake Updater"
      - name: Set git email for commits
        run: git config user.email "flake-updater@binarin.info"
      - name: Commit updates
        run: git commit --allow-empty -am "Bump inputs"
      - name: Run flake check
        run: nix flake check
      - name: Push to flake-bump branch
        run: git push --force origin master:flake-bump
      - name: API auth
        run: |
          set -x
          fj -H forgejo.lynx-lizard.ts.net auth logout forgejo.lynx-lizard.ts.net || true
          echo "${{ secrets.PR_TOKEN }}" | fj -H forgejo.lynx-lizard.ts.net auth add-key nixos-config-bumper
      - name: Maybe create PR
        run: fj -H forgejo.lynx-lizard.ts.net pr create -r binarin/nixos-config --base master --head flake-bump --body "Bump flake inputs" "Bump everything" || true
