on:
  schedule:
    - cron: "13 10 * * Mon"
  workflow_dispatch: {}

concurrency:
  group: flake-update
  cancel-in-progress: false

jobs:
  update-flake:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: ./.forgejo/actions/git-crypt-unlock
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Update flake inputs
        run: nix flake update
      - name: Run autofollow
        run: nix run .#write-flake
      - name: Format code
        run: nix fmt
      - name: Run flake check
        run: nix flake check
      - name: Set git username for commits
        run: git config user.name "Automatic Flake Updater"
      - name: Set git email for commits
        run: git config user.email "flake-updater@binarin.info"
      - name: Commit updates
        run: git commit -am "Bump inputs" || echo "No changes to commit"
      - name: Push to flake-bump branch
        run: git push --force origin HEAD:flake-bump

  define-matrix:
    runs-on: native
    needs: update-flake
    outputs:
      configurations: ${{ steps.define.outputs.configurations }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: flake-bump
      - uses: ./.forgejo/actions/git-crypt-unlock
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - id: define
        run: |
          echo "configurations=$(nix run .#env-aware-nix-run -- .#ncf -- ci matrix)" >> "$FORGEJO_OUTPUT"

  build-configs:
    name: build ${{ matrix.config }}
    runs-on: native
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.define-matrix.outputs.configurations) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: flake-bump
      - uses: ./.forgejo/actions/git-crypt-unlock
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: ./.forgejo/actions/build-nix
        with:
          config: ${{ matrix.config }}
          output-link: temp-result/${{ matrix.config }}

  create-pr:
    runs-on: native
    needs: build-configs
    steps:
      - uses: actions/checkout@v4
        with:
          ref: flake-bump
      - uses: ./.forgejo/actions/forgejo-api-auth
        with:
          token: ${{ secrets.PR_TOKEN }}
          key-name: nixos-config-bumper
      - name: Maybe create PR
        run: fj -H forgejo.lynx-lizard.ts.net pr create -r binarin/nixos-config --base master --head flake-bump --body "Bump flake inputs" "Bump everything" || true
