on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  flake-check:
    name: nix flake check
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.forgejo/actions/git-crypt-unlock
        if: github.event_name == 'push'
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: ./.forgejo/actions/fake-unlock
        if: github.event_name == 'pull_request_target'
      - run: nix flake check
