on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  define-matrix:
    runs-on: native
    outputs:
      configurations: ${{ steps.define.outputs.configurations }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: fake git-crypt unlock
        run: nix run .#ncf -- ci fake-unlock
      - id: define
        run: |
          echo "configurations=$(nix run .#ncf -- ci matrix)" >> "$FORGEJO_OUTPUT"

  nixos-configuration:
    runs-on: native
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        nixosConfiguration: ${{ fromJSON(needs.define-matrix.outputs.configurations) }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: fake git-crypt unlock
        run: nix run .#ncf -- ci fake-unlock
      - run: nix run .#ncf -- build nixos ${{ matrix.nixosConfiguration }} --no-nom

  check:
    runs-on: native
    needs:
      - nixos-configuration
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: fake git-crypt unlock
        run: nix run .#ncf -- ci fake-unlock
      - run: nix flake check
