on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  define-matrix:
    runs-on: native
    outputs:
      configurations: ${{ steps.define.outputs.configurations }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: fake git-crypt unlock
        run: nix run .#ncf -- ci fake-unlock
      - id: define
        run: |
          echo "configurations=$(nix run .#ncf -- ci matrix)" >> "$FORGEJO_OUTPUT"
          cat "$FORGEJO_OUTPUT"

  nixos-configuration:
    name: build ${{ matrix.config }}
    runs-on: native
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.define-matrix.outputs.configurations) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: fake git-crypt unlock
        run: nix run .#ncf -- ci fake-unlock
      - run: |
          BUILD_PATH=$(nix run .#ncf -- ci build-path '${{ matrix.config }}')
          nix build "$BUILD_PATH" --no-link --print-out-paths
