---
on:
  workflow_dispatch: {}
jobs:
  build-iso-wifi:
    runs-on: native
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: ./.forgejo/actions/git-crypt-unlock
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Build WiFi-enabled ISO
        run: nix run .#env-aware-nix-run -- .#ncf -- iso build-wifi --output "$RUNNER_TEMP/nixos-wifi.iso" --password-file files/agares-guest.git-crypt
      - name: Upload ISO to garage
        env:
          AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED
          AWS_RESPONSE_CHECKSUM_VALIDATION: WHEN_REQUIRED
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: s3cmd --host=s3.lynx-lizard.ts.net --host-bucket=s3.lynx-lizard.ts.net put "$RUNNER_TEMP/nixos-wifi.iso" s3://web.binarin.info/files/
