on: [push]
jobs:
  # check:
  #   runs-on: native
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: nix flake check

  list-nixos-configurations:
    runs-on: native
    outputs:
      nixosConfigurations: ${{ steps.set-matrix.outputs.nixosConfigurations }}
    steps:
      - uses: actions/checkout@v4
      - run: (echo -n "nixosConfigurations="; nix flake show --quiet --json | jq  -c '.nixosConfigurations | keys') >> $GITHUB_OUTPUT
        id: set-matrix

  nixos-configuration:
    runs-on: native
    name: ${{ matrix.nickname }}
    needs: list-nixos-configurations
    if: needs.list-nixos-configurations.outputs.nixosConfigurations != ''
    strategy:
      fail-fast: false
      matrix:
        nixosConfiguration: $${ fromJSON(needs.list-nixos-configurations.outputs.nixosConfigurations) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $${ needs.list-nixos-configurations.outputs.nixosConfigurations }}
      - run: >-
          nix build "$(pwd)#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel"
            --keep-going -j auto
            -o "$HOME/.cache/nixos-config/master/nixos-configuration/${{ matrix.nixosConfiguration }}"
