on:
  push:
    branches:
      - master

jobs:
  define-matrix:
    runs-on: native
    outputs:
      configurations: ${{ steps.define.outputs.configurations }}
    steps:
      - uses: actions/checkout@v4
      - id: define
        run: |
          echo "configurations=$(nix run .#env-aware-nix-run -- .#ncf -- ci matrix)" >> "$FORGEJO_OUTPUT"

  nixos-configuration:
    name: build ${{ matrix.config }}
    runs-on: native
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.define-matrix.outputs.configurations) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.forgejo/actions/git-crypt-unlock
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: ./.forgejo/actions/build-nixos-config
        with:
          config: ${{ matrix.config }}
          output-link: ~/.cache/nixos-config/nixos-configuration/${{ matrix.config }}
          paths-file: ~/.cache/nixos-config/nixos-configuration/${{ matrix.config }}.paths
      - uses: ./.forgejo/actions/sign-and-push-cache
        with:
          paths-file: ~/.cache/nixos-config/nixos-configuration/${{ matrix.config }}.paths
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          signing-key-pem: ${{ secrets.GARAGE_STORE_PRIV_KEY_PEM }}
