on: [push]
jobs:
  nixos-configuration:
    runs-on: native
    strategy:
      fail-fast: false
      matrix:
        nixosConfiguration:
          - valak
          - media
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ needs.list-nixos-configurations.outputs.nixosConfigurations }}
      - run: nix build "$(pwd)#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel" --keep-going -j auto -o "$HOME/.cache/nixos-config/master/nixos-configuration/${{ matrix.nixosConfiguration }}"
