on:
  push:
    branches:
      - master
  pull_request:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ncf-tests:
    name: ncf tests
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: run ncf tests
        run: nix develop --ignore-environment .#devShells.x86_64-linux.default --command pytest tools/ncf -v
