on:
  push:
    branches:
      - master
  pull_request:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  nct-tests:
    name: nct tests
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: cargo test
        run: nix run .#env-aware-nix-develop -- .#devShells.x86_64-linux.nct --command cargo test --manifest-path tools/nct/Cargo.toml
      - name: build flake package
        run: nix build .#nct --print-build-logs
