---
name: 'Sign and Push to Cache'
description: 'Sign Nix store paths and push to S3 cache'
inputs:
  paths-file:
    description: 'File containing store paths to sign and push (one per line)'
    required: true
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  signing-key-pem:
    description: 'Private key for signing (PEM format)'
    required: true
  niks3-api-token:
    description: 'API token to push to niks3'
    required: true
runs:
  using: composite
  steps:
    - name: sign and push to niks3
      shell: bash
      env:
        PATHS_FILE: ${{ inputs.paths-file }}
        NIKS3_API_TOKEN: ${{ inputs.niks3-api-token }}
      run: |
        if [[ ! -f "$PATHS_FILE" ]]; then
          echo "Error: paths-file does not exist: $PATHS_FILE"
          exit 1
        fi

        # XXX recently merged, let's wait for https://codeberg.org/forgejo/forgejo/issues/2389 to be released
        # export NIKS3_AUTH_TOKEN_FILE="$(mktemp)"
        # export NIKS3_SERVER_URL=https://niks3.lynx-lizard.ts.net/
        # trap 'rm -f "$NIKS3_AUTH_TOKEN_FILE"' EXIT
        # curl --output "$NIKS3_AUTH_TOKEN_FILE" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://niks3.lynx-lizard.ts.net"
        # cat "$PATHS_FILE" | xargs niks3 push --debug
        # rm -f "$NIKS3_AUTH_TOKEN_FILE"
        cat "$PATHS_FILE" | xargs --max-chars=1944546 --max-args=20000 niks3 push --auth-token "$NIKS3_API_TOKEN" --server-url "https://niks3.lynx-lizard.ts.net"
