apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.2.33
      user: binarin
      port: 22
      keyPath: /home/binarin/.ssh/id_ed25519
    role: controller+worker
  - ssh:
      address: 192.168.2.34
      user: binarin
      port: 22
      keyPath: /home/binarin/.ssh/id_ed25519
    role: controller+worker
  - ssh:
      address: 192.168.2.35
      user: binarin
      port: 22
      keyPath: /home/binarin/.ssh/id_ed25519
    role: controller+worker
  k0s:
    version: 1.22.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 192.168.2.36
          sans:
          - 192.168.2.36
        extensions:
          helm:
            repositories:
            - name: traefik
              url: https://helm.traefik.io/traefik
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            - name: longhorn
              url: https://charts.longhorn.io
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "10.3.6"
              namespace: traefik-system
            - name: longhorn
              chartname: longhorn/longhorn
              version: "1.2.0"
              namespace: longhorn-system"
            - name: metallb
              chartname: bitnami/metallb
              version: "2.5.5"
              namespace: metallb-system
              values: |2
                configInline:
                  address-pools:
                  - name: generic-cluster-pool
                    protocol: layer2
                    addresses:
                    - 192.168.2.80-192.168.2.99
