---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 3
  image: pivotalrabbitmq/rabbitmq:v3.9.7-otp-max
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  service:
    type: ClusterIP
  persistence:
    storageClassName: longhorn
    storage: 5Gi
  # override:
  #   statefulSet:
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #             - name: rabbitmq
  #               imagePullPolicy: Always
  #               securityContext:
  #                 runAsUser: 0
