---
- name: Restart sshd
  block:
    - name: Test sshd_config
      ansible.builtin.command: sshd -t
      changed_when: false
    - name: Restart
      ansible.builtin.service: name=sshd state=restarted
