---
- name: Create /etc/ssh/trusted_user_ca_keys
  template:
    src: trusted_user_ca_keys.j2
    dest: /etc/ssh/trusted_user_ca_keys
    owner: root
    group: root
    mode: "0644"
- name: Create /etc/ssh/sshd_config.d/10-trusted_user_ca_keys.conf
  copy:
    content: "TrustedUserCaKeys /etc/ssh/trusted_user_ca_keys\n"
    dest: /etc/ssh/sshd_config.d/10-trusted_user_ca_keys.conf
    force: yes
  notify: restart sshd
- name: Ensure that /etc/ssh/sshd_config.d/*.conf is sourced by sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    insertbefore: BOF
  notify: restart sshd
