#!/usr/bin/env zsh
set -x
exec 2> /tmp/deb
set -eu
set -o pipefail

top-level() {
    item "LOCAL" local-shell "$@"
    item "HOME" menu:home-servers "$@"
}

local-shell() {
    local prefix="$4"
    switch-or-run-foot "$prefix" -e tmux new-session -A -s binarin
}

home-servers() {
    item "amon" mosh-amon "$@"
    item "amon-root" mosh-amon-root "$@"
    item "naberius-root" mosh-naberius-root "$@"
    item "raum-root" mosh-raum-root "$@"
    item "bael-root" mosh-bael-root "$@"
    item "hass" mosh-ts "$@"
    item "barbatos-root" mosh-ts "$@"
    item "ishamael" et-ts "$@"
}

find-and-focus-window-niri() {
    local title="$1"

    if niri msg --json windows | jq -r '.[].title' | grep -q -F "$title"; then
        local window_id=$(niri msg --json windows | jq -r ".[] | select(.title == \"$title\") | .id")
        niri msg action focus-window --id "$window_id"
        return 0
    else
        return 1
    fi
}

find-and-focus-window-hyprland() {
    local title="$1"

    local titleEscaped
    titleEscaped=$(sed 's/[^^]/[&]/g; s/\^/\\^/g' <<<"$title")

    if hyprctl clients -j | jq -r '.[].title' | grep -q -F "$title"; then
        hyprctl dispatch focuswindow title:"$titleEscaped"
        return 0
    else
        return 1
    fi
}

find-and-focus-window() {
    local title="$1"

    case "$XDG_SESSION_DESKTOP" in
        niriSession)
            find-and-focus-window-niri "$title"
            ;;
        hyprland)
            find-and-focus-window-hyprland "$title"
            ;;
        *)
            echo "Unsupported desktop session: $XDG_SESSION_DESKTOP" >&2
            return 1
            ;;
    esac
}

switch-or-run-foot() {
    local title="${1:?}"; shift

    if find-and-focus-window "$title"; then
        exit 0
    else
        exec uwsm app -t service -a "sshmenu-$title" -- foot --title "$title" "$@"
    fi
}

tmux-command() {
    local name="${1:?}"
    echo ": ; tmux new-session -A -s '$name'";
}

mosh-amon() {
    local prefix="$4"
    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh binarin@amon.ts.binarin.info -- tmux new-session -A -s binarin
}

mosh-amon-root() {
    local prefix="$4"
    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh root@amon.ts.binarin.info -- tmux new-session -A -s binarin
}

mosh-naberius-root() {
    local prefix="$4"
    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh root@barbatos.ts.binarin.info -- tmux new-session -A -s binarin
}

mosh-raum-root() {
    local prefix="$4"
    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh root@raum.ts.binarin.info -- tmux new-session -c /usr/local/bin/zsh -A -s binarin
}

mosh-bael-root() {
    local prefix="$4"
    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh root@192.168.2.68 -- tmux new-session -c /usr/local/bin/zsh -A -s binarin
}

mosh-ts() {
    local display_name="$1"
    local prefix="$4"

    local host="$display_name"
    local user_part=""

    if [[ "$host" =~ ^(.*)-root$ ]]; then
        user_part="root@"
        host="${match[1]}"
    fi

    switch-or-run-foot "$prefix" --override=colors.background=001800 -e mosh $user_part$host.lynx-lizard.ts.net -- tmux new-session -A -s binarin
}

et-ts() {
    local display_name="$1"
    local prefix="$4"

    local host="$display_name"
    local user_part=""

    if [[ "$host" =~ ^(.*)-root$ ]]; then
        user_part="root@"
        host="${match[1]}"
    fi

    switch-or-run-foot "$prefix" --override=colors.background=001800 -e et $user_part$host.lynx-lizard.ts.net -c "tmux new-session -A -s binarin"
}



mosh-naberius() {
    local prefix="$4"
    switch-or-run-rxvt "$prefix" -bg '#001800' -e ssh -t 5.9.106.77 -- sh -c "$(tmux-command binarin)"
}

mosh-aim() {
    local prefix="$4"
    switch-or-run-rxvt "$prefix" -bg '#001800' -e ssh -t aim.localdomain -- sh -c "$(tmux-command binarin)"
}

mosh-barbatos() {
    local prefix="$4"
    switch-or-run-rxvt "$prefix" -bg '#001800' -e ssh -t root@192.168.2.25 -- sh -c "$(tmux-command binarin)"
}

mosh-hass() {
    local prefix="$4"
    switch-or-run-rxvt "$prefix" -bg '#001800' -e ssh -t hass -- sh -c "$(tmux-command binarin)"
}

ssh-nix-build() {
    local prefix="$4"
    switch-or-run-rxvt "$prefix" -bg '#001800' -e ssh -t nix-build -- sh -c "$(tmux-command binarin)"
}

gcloud-ssh() {
    local display_name="$1"
    local prefix="$4"

    switch-or-run-rxvt "$prefix" -bg '#001800' -e gcloud beta compute ssh --zone $GCP_ZONE $display_name --tunnel-through-iap --project $GCP_PROJECT -- -t -- sh -c "$(tmux-command binarin)"
}


item() {
    local display_name="$1"
    local function_to_call="$2"
    local mode="$3"
    local prefix="$4"

    local our_path
    local our_idx=$menu_idx
    menu_idx=$((menu_idx + 1))

    if [[ -z $prefix ]]; then
        our_path="$display_name"
    else
        our_path="$prefix|$display_name"
    fi

    case "$mode" in
        list)
            menu_labels+=("$display_name")
            ;;
        run)
            local run_idx="$5"
            if [[ $run_idx == $our_idx ]]; then
                if [[ $function_to_call =~ '^menu:(.+)$' ]]; then
                    exec-menu "$match[1]" "$our_path"
                else
                    $function_to_call $display_name $function_to_call run $our_path
                fi
            else
                return 0
            fi
        ;;
    esac
}

exec-menu() {
    local menu_function="$1"
    local prefix="$2"
    shift 2

    local -a menu_labels
    local menu_idx=1
    $menu_function list "$prefix"

    local idx
    clear
    for idx in $(seq 1 ${#menu_labels}); do
        printf "%s. %s\n" $(printf '%x' "$(($idx + 97 - 1))" | xxd -p -r) "$menu_labels[$idx]"
    done

    local choice
    read -sk choice
    if [[ $choice == $'\n' ]]; then
        choice='a'
    fi

    choice=$(( $(printf '%d' "'$choice'") - 97 + 1))

    if [[ $choice -lt 1 || $choice -gt ${#menu_labels} ]]; then
        exit 1
    fi

    local menu_idx=1
    $menu_function run "$prefix" $choice
}

if [[ "$#" -gt 0 ]]; then
    exec-menu top-level "SH"
else
    urxvt -title "FAST_CHOICE" -fn "xft:IosevkaTerm Nerd Font:pixelsize=50" -geometry 30x10 -sb -e zsh -c "$0 go"
fi
