name: xmonad-config
version: 0.1.0.0

default-extensions:
  - FlexibleInstances
  - ScopedTypeVariables
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards

dependencies:
  - base
  - xmonad
  - xmonad-contrib
  - containers
  - stm
  - unix
  - X11
  - lens
  - data-default
  - utf8-string

executable:
  main: Main.hs
  source-dirs:
    - .
