---
- hosts: manage_ssh_access
  tags: ssh
  vars_files:
    ./ssh-public-keys.yaml
  handlers:
    - import_tasks: handlers/restart-sshd.yaml
  tasks:
    - import_tasks: tasks/ssh-trusted-ca-keys.yaml
    - import_tasks: tasks/authorized-keys.yaml
