---
- hosts: pve
  become: true
  vars:
    zfs_exporter_version: '2.3.4'
    # zfs_exporter_options: '--collector.dataset-snapshot'
    vmagent_remote_write_host: http://192.168.2.2:8428
    vmagent_scrape_config:
      global:
        external_labels:
          host: "{{ inventory_hostname }}"
      scrape_configs:
        - job_name: "node"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:9100"]
        - job_name: "zfs"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:9134"]
        - job_name: "vmagent"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:8429"]

  # roles:
  #   - victoriametrics.cluster.vmagent
  #   - prometheus.prometheus.node_exporter
  #   - aroberts.zfs_exporter
  handlers:
    - name: Update initramfs
      listen:
        - update initramfs
        - update initrd
      ansible.builtin.command:
        cmd: >
          update-initramfs -k all -u
  tasks:
    - name: Install some generic linux tools
      package:
        state: present
        name:
          - emacs-nox
          - sysstat
          - iotop
          - net-tools #netstat
          - tmux
          - mosh
    - name: Copy sanoid config
      copy:
        src: "{{ inventory_hostname }}-sanoid.conf"
        dest: /etc/sanoid/sanoid.conf
        mode: '0644'
    - name: Install Clevis with necessary pins/integrations
      notify: update initramfs
      package:
        state: present
        name:
          - clevis
          - clevis-tpm2
          - clevis-initramfs
          - clevis-luks

- hosts: pve
  become: true
  tasks:
    - name: Set UDP receive buffer size (for tailscale in CTs)
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: '10000000'
    - name: Set UDP send buffer size (for tailscale in CTs)
      ansible.posix.sysctl:
        name: net.core.wmem_max
        value: '10000000'

- hosts: pve
  become: true
  tasks:
    - name: Install packages to use SSH key in tpm 2.0
      package:
        state: present
        name:
          - libtpm2-pkcs11-tools
          - libtpm2-pkcs11-1
    - name: Use SSH key from tpm 2.0 by default
      copy:
        content: |
          Host *
            PKCS11Provider /usr/lib/x86_64-linux-gnu/libtpm2_pkcs11.so.1
        dest: /etc/ssh/ssh_config.d/enable-tpm2-pkcs11.conf
        mode: '0644'
        owner: root

- hosts: bael
  become: true
  tasks:
    - name: Copy and enable hourly raum->bael backup script
      copy:
        src: backup-raum
        dest: /usr/local/bin/backup-raum
        mode: '0755'
        owner: root
        group: root

    - name: create the backup-raum.service file
      copy:
        src: backup-raum.service
        dest: /etc/systemd/system/backup-raum.service

    - name: create the backup-raum.timer file
      copy:
        src: backup-raum.timer
        dest: /etc/systemd/system/backup-raum.timer

    - name: make sure that the backup-raum.timer is started
      systemd:
        name: backup-raum.timer
        state: started
        enabled: yes
        daemon_reload: yes


- hosts: pve_at_home
  tags: networking
  become: true
  vars:
    ip_allocation: "{{ lookup('file', 'ip-allocation.yaml') | from_yaml }}"
  tasks:
    - name: Redirect tailscale DNS names to local IPs
      lineinfile:
        dest: /etc/hosts
        state: present
        line: '{{ ip_allocation[item].home.primary.address  }} {{ item }}.lynx-lizard.ts.net'
      with_items: "{{ groups['pve_at_home'] | select('ne', inventory_hostname) }}"
