---
- hosts: pve
  become: true
  vars:
    zfs_exporter_version: '2.3.4'
    # zfs_exporter_options: '--collector.dataset-snapshot'
    vmagent_remote_write_host: http://192.168.2.2:8428
    vmagent_scrape_config:
      global:
        external_labels:
          host: "{{ inventory_hostname }}"
      scrape_configs:
        - job_name: "node"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:9100"]
        - job_name: "zfs"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:9134"]
        - job_name: "vmagent"
          scrape_interval: "10s"
          static_configs:
            - targets: ["127.0.0.1:8429"]

  roles:
    - victoriametrics.cluster.vmagent
    - prometheus.prometheus.node_exporter
    - aroberts.zfs_exporter
  tasks:
    - name: Install some generic linux tools
      package:
        state: present
        name:
          - emacs-nox
          - sysstat
          - iotop
          - net-tools #netstat
    - name: Copy sanoid config
      copy:
        src: "{{ inventory_hostname }}-sanoid.conf"
        dest: /etc/sanoid/sanoid.conf
        mode: '0644'
- hosts: bael.lynx-lizard.ts.net
  become: true
  tasks:
    - name: Copy and enable hourly raum->bael backup script
      copy:
        src: backup-raum
        dest: /etc/cron.hourly/backup-raum
        mode: '0755'
        owner: root
        group: root
