collections:
  - name: victoriametrics.cluster
    version: "2.52.0"
  - name: prometheus.prometheus
    version: "0.30.0"
  - name: ansible.posix
    version: "2.2.1"
  - name: artis3n.tailscale
    version: "1.2.1"

roles:
  - name: aroberts.zfs_exporter
    version: "v1.0.0"
