common: ENC[AES256_GCM,data:YL6EHWZqBw9j7iPbFSqIhhMCYtNa5nbbomPJvT0s0XgKxG0xqwN7IJixXQ581d1eoey6kPed1W9pHoRRuNEN53Ox2rkj2AKTbDjGGz3RysXIN+X5A5gsAo6mQ5RHW8kzv71U3N9NqZjYTOgMKmxObl6PcqNfBWlEqmJTKzc2g0YYdkoupVXpwtK/CrITk+ydg3DyDPeL4Pwo/LCpTjzftBBpKq9K6AeiDEk=,iv:9I1vBTmzPd037wM3z3cKjFdk+IJrUKltiE4fl/poMeA=,tag:DOFA2CV+m/VHEnm2HfgnzQ==,type:str]
offsite: ENC[AES256_GCM,data:JMLHW4dlHWOwBZFDQZMwRBmMqbtuJa8ezuOqzLgTQGUG07NGWjieXYaXhTMezY4xjGW0ylBTAG8uxFVqG8oEkbUB971cQEC2qmNLwLEc7whcUEl+zrZ0JScbEf0JMyi0e67EnQ9MRZaI+kdINlmYwl1LR+onh0bFEx4yCA+J0079UQvdAoyeebUsji/5U51qILRc4qzAil4=,iv:84u2szHb5SS5iy1J0pvkUmMsbh5jxuBAsKo0LAyyzAw=,tag:7VVfe6E1APbViE+SySvxVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeHc4a3BqSjN4bmhwR1lz
            aStKdGQ1ZDk2K3NZcGVnT2RqMHVXQlJRdEhjCnU3SU0wMEorQ2J4QjlVSU00NjE4
            d29FWjV5ZzR4Zkg4U1NIbEpMMEh1U1EKLS0tIDFhRW43Ri9BT29JWDUxbE1CQ2dt
            eXR5N3RSUlN2SEZuamlhLys5NDY0UDQKXITicVuyh/eeeKynJQa7XNV8bNZMIp0a
            s8zs0UV8wAzvHcTCV4Vv3VAy2XdzQQ2Af7SKPPCEFPKJOqxxhUA6AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ec9gz6f685mn8pdrz48qm4vq7qzpzcz48vgkcty9aa665evra9lq2uz3s2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkVyeTErNU1wRHlPVEUx
            ZUJMK3FUOXgxeFNtSSs4bHMrUkFVcGltK0NVCk9iZDlDcFhCREhCcVFkeE42VnVn
            dU9JRU55NUZTTC94QmRwTlpDemVMVGcKLS0tIFFoamxZWXZGQzArMkt1eko4WHVX
            REVQU0s5Ny9yMXVjTFBvWEJkR1hEVjAK9EMWiI6XIWJuG7UokPKZLrcEPxuXKZfm
            w0lg4AKLo/+xtHqNty1P9ksKpNKhnDuglQ/GKkO7dV6VRTX4h9gYIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvu92xmh3w23ghey4l0epcs27m89f3nswzs5twgnel36xxu42f4sfsv023
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S0prdlhib3ZuQnVGZjdO
            Z0V6Y3ZzSjFsUjZoNjNtUzhiU3JkMHJRc1RVCmRMb2lYRkljYWphZ251Tk45RGl3
            TUJqVjFybDBnbWdRdmd6aGZSYUtwcDQKLS0tIEhpSkIrQVhjUWVIUG9pVndxRE9i
            c1ZYWll0UktQSE56NWppdFI4d3RvK0UKUXXDiSRGaI7wGcxv+h0x0F/04s4uRRg2
            Ll2O0rkoa8mrMJVlxQQmfG7o2aXEUlmFnlnriNlU2kKuJAglyjDGqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uq5t9y9sapf54enpahql6ncfqvttrwwxk459vtkegu4slk9ef7s6pp2uw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcVo4U0V4RGYrSEo3elRW
            K2s1QTYzNzRNVGUxZmtIWVZzRTJWSC9kZGh3ClREV3F1dWV5ZlRIclhhWTFFSTJZ
            VlJvcWw3dWErcWRwRTI4dDZOL0JpYXcKLS0tIHQvUXJoMFpzK29RVU85aHVwSXhU
            QXZTOGxNTTNCb012QUpUbFBmVDBUVkUKshBbeg7YjADZ4PNgCu5Dbcf7W9Ehv8Xl
            DvSOrOMmMvZX7E+By5S5Zuk7G6+wUP8oBdypDt/H/2wa22nLmdJ6xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyfyczqyt6a20um7jlzrvd0p85qslqvkycm4d8kqkwey24543egqwwqha2
    lastmodified: "2026-07-30T19:04:01Z"
    mac: ENC[AES256_GCM,data:509v3I0DmpUxRIEry2I1Eg0ocB8frHHSHm/BrnU4nMC755KcPLtob9gecjQV2ZQwprshqGt7/aW9BqIXrnNILIBV8gW9bmjwWgUAdjSkNVQGT0V0yMm47yVjbn7h18omYoh8L2WgUoUTWFwvtcrW/FQEG1j5iOtRYj2Va4FlS0o=,iv:DXvdk0suiWEyxnQZGN4wDqAiYcSv/nSA3Ekk0TREiSQ=,tag:Ajql8An0JSpSl2wnsOxSLg==,type:str]
    pgp:
        - created_at: "2026-07-30T19:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjUagJu2XQwUSAQdAUxzcHIlxc/JsviIzXx83jd82N/ajUIn0RodQo3nxLDYw
            12UbWQbyiIjmza9eMz6A9CZX0t99IgDFfpghkCijOK0stUMGYB5IVYblRu6/+S6l
            0l4BG8bnWcGAUaDPtcj8n79GCeQMaqTcOrYCdm/Cpo3tV2O96Tu6HabhmiK4FU0l
            6znxRRwA6x7H8LGYIuTCy8XcvLw9R5Y6GXJXlpnbLyyVYbukECWGXFzZTkFNLhzY
            =+qdW
            -----END PGP MESSAGE-----
          fp: 7668F12EF30BE2A802E1E13E6D4365C3B5E703F5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
