common: ENC[AES256_GCM,data:7gO3dLKyMHsVGs+jeX2UTaANgJW8IYnyFfVaIWzOiKatIDOED1U1Ruf5Jim9PO4lzl/BCtt9AZN2NHLP7k+TC84RbK8vR6Hv1JGGae8xisMNYjKex/HqpFSe9FB890UMAXg/FuTPrR64qaGxQQHnWHTBd66m4CB9m5zGLWVv62Na45zjy0QsJpw4magtXBLAHhMLQG7cQ8OtVVnAOcR7h6nRT3rj3Ag+oRFQe4UavB49l7UAbsJOf6TcQmxMetZDBGLddYuJ1bh9BEoKGZEExxGCfe+0Ro36jhlas6zEs6qTfVpKoon6G4rwOB9rEBooKFanvLs4WXzoqlwPC/FXEAdgSY9CGlVlN8zEttOsYGk=,iv:vn1hTANUKZT3MUwekGfT+4BSVN3+Rc1xaGsJtyGvhSk=,tag:jXdLoZcOM5b6R2Oxm6wucg==,type:str]
offsite: ENC[AES256_GCM,data:JMLHW4dlHWOwBZFDQZMwRBmMqbtuJa8ezuOqzLgTQGUG07NGWjieXYaXhTMezY4xjGW0ylBTAG8uxFVqG8oEkbUB971cQEC2qmNLwLEc7whcUEl+zrZ0JScbEf0JMyi0e67EnQ9MRZaI+kdINlmYwl1LR+onh0bFEx4yCA+J0079UQvdAoyeebUsji/5U51qILRc4qzAil4=,iv:84u2szHb5SS5iy1J0pvkUmMsbh5jxuBAsKo0LAyyzAw=,tag:7VVfe6E1APbViE+SySvxVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeHc4a3BqSjN4bmhwR1lz
            aStKdGQ1ZDk2K3NZcGVnT2RqMHVXQlJRdEhjCnU3SU0wMEorQ2J4QjlVSU00NjE4
            d29FWjV5ZzR4Zkg4U1NIbEpMMEh1U1EKLS0tIDFhRW43Ri9BT29JWDUxbE1CQ2dt
            eXR5N3RSUlN2SEZuamlhLys5NDY0UDQKXITicVuyh/eeeKynJQa7XNV8bNZMIp0a
            s8zs0UV8wAzvHcTCV4Vv3VAy2XdzQQ2Af7SKPPCEFPKJOqxxhUA6AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ec9gz6f685mn8pdrz48qm4vq7qzpzcz48vgkcty9aa665evra9lq2uz3s2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkVyeTErNU1wRHlPVEUx
            ZUJMK3FUOXgxeFNtSSs4bHMrUkFVcGltK0NVCk9iZDlDcFhCREhCcVFkeE42VnVn
            dU9JRU55NUZTTC94QmRwTlpDemVMVGcKLS0tIFFoamxZWXZGQzArMkt1eko4WHVX
            REVQU0s5Ny9yMXVjTFBvWEJkR1hEVjAK9EMWiI6XIWJuG7UokPKZLrcEPxuXKZfm
            w0lg4AKLo/+xtHqNty1P9ksKpNKhnDuglQ/GKkO7dV6VRTX4h9gYIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvu92xmh3w23ghey4l0epcs27m89f3nswzs5twgnel36xxu42f4sfsv023
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S0prdlhib3ZuQnVGZjdO
            Z0V6Y3ZzSjFsUjZoNjNtUzhiU3JkMHJRc1RVCmRMb2lYRkljYWphZ251Tk45RGl3
            TUJqVjFybDBnbWdRdmd6aGZSYUtwcDQKLS0tIEhpSkIrQVhjUWVIUG9pVndxRE9i
            c1ZYWll0UktQSE56NWppdFI4d3RvK0UKUXXDiSRGaI7wGcxv+h0x0F/04s4uRRg2
            Ll2O0rkoa8mrMJVlxQQmfG7o2aXEUlmFnlnriNlU2kKuJAglyjDGqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uq5t9y9sapf54enpahql6ncfqvttrwwxk459vtkegu4slk9ef7s6pp2uw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcVo4U0V4RGYrSEo3elRW
            K2s1QTYzNzRNVGUxZmtIWVZzRTJWSC9kZGh3ClREV3F1dWV5ZlRIclhhWTFFSTJZ
            VlJvcWw3dWErcWRwRTI4dDZOL0JpYXcKLS0tIHQvUXJoMFpzK29RVU85aHVwSXhU
            QXZTOGxNTTNCb012QUpUbFBmVDBUVkUKshBbeg7YjADZ4PNgCu5Dbcf7W9Ehv8Xl
            DvSOrOMmMvZX7E+By5S5Zuk7G6+wUP8oBdypDt/H/2wa22nLmdJ6xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyfyczqyt6a20um7jlzrvd0p85qslqvkycm4d8kqkwey24543egqwwqha2
    lastmodified: "2026-09-21T16:02:55Z"
    mac: ENC[AES256_GCM,data:3E2hjxyUUDWmZOryRiPmHJvr97fr8i6WMO+EXhnu3sqIntjir1yukLKcPXMPa7o4HGn+O2hSQ8wyWNYWQGEM0MyM4S9K1omR+icVttOtf7K3PxBBNjzl2FT6UQGjreavT70TlYWBse1UEHpGKHOljhgOCSPFlyYhQ/xQUIYH4uM=,iv:cTTl6L9nfpqmMFxnEdQ55AMCT0fMIYcV0reJ1wGCkzM=,tag:zNshrRNxhkRnbRYExNfpwg==,type:str]
    pgp:
        - created_at: "2026-07-30T19:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjUagJu2XQwUSAQdAUxzcHIlxc/JsviIzXx83jd82N/ajUIn0RodQo3nxLDYw
            12UbWQbyiIjmza9eMz6A9CZX0t99IgDFfpghkCijOK0stUMGYB5IVYblRu6/+S6l
            0l4BG8bnWcGAUaDPtcj8n79GCeQMaqTcOrYCdm/Cpo3tV2O96Tu6HabhmiK4FU0l
            6znxRRwA6x7H8LGYIuTCy8XcvLw9R5Y6GXJXlpnbLyyVYbukECWGXFzZTkFNLhzY
            =+qdW
            -----END PGP MESSAGE-----
          fp: 7668F12EF30BE2A802E1E13E6D4365C3B5E703F5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
